baseURL = "https://kuba86.github.io/"
title = "kuba86 - Scala Engineer"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 2000

[params]
  author = "Jakub Błaszczyk"
  info = "Scala Engineer"
  description = "kuba86's personal website. Scala, Akka, Blog, Developer, Software, Engineer"
  keywords = "scala,akka,blog,developer,software,engineer"
  avatarurl = "img/profile.jpg"
  favicon_16 = ""
  favicon_32 = ""
  touchicon = ""
#  footercontent = "Enter a text here."
  since = 2021
  enableTwemoji = false
  colorScheme = "dark"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/kuba86/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 1
  url = "https://www.linkedin.com/in/blaszczykjakub/"
[[params.social]]
  name = "RSS"
  icon = "fa fa-rss fa-2x"
  weight = 1
  url = "https://kuba86.github.io/index.xml"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "Tags"
  weight = 2
  url = "tags/"
#[[menu.main]]
#  name = "Series"
#  weight = 3
#  url = "series/"