baseURL = "https://kuba86.com/"
title = "kuba86 · Scala Engineer"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"
pygmentsStyle = "monokai"
pygmentsCodeFences = true
pygmentsCodeFencesGuessSyntax = true
paginate = 5000

[params]
  author = "kuba86"
  info = "Scala Engineer"
  description = "kuba86's personal website about Scala and journey as a software engineer"
  keywords = "scala,blog,developer,software,engineer,kuba86"
  avatarurl = "img/profile.jpg"
  favicon_16 = "img/favicon_16.png"
  favicon_32 = "img/favicon_32.png"
  touchicon = "img/touchicon.png"
  since = 2021
  enableTwemoji = false
  colorScheme = "dark"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/kuba86/"
[[params.social]]
  name = "LinkedIn"
  icon = "fa fa-linkedin fa-2x"
  weight = 1
  url = "https://www.linkedin.com/in/blaszczykjakub/"
[[params.social]]
  name = "dev.to"
  icon = "fa fa-dev-to fa-2x"
  weight = 1
  url = "https://dev.to/kuba86"
[[params.social]]
  name = "RSS"
  icon = "fa fa-rss fa-2x"
  weight = 1
  url = "https://kuba86.github.io/index.xml"

[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "Tags"
  weight = 2
  url = "tags/"
